#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 20

enum ts_symbol_identifiers {
  sym_id = 1,
  anon_sym_AT_AT_LBRACK = 2,
  anon_sym_RBRACK_AT_AT = 3,
  anon_sym_AT = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_record = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_get = 11,
  anon_sym_post = 12,
  anon_sym_SEMI = 13,
  anon_sym_COMMA = 14,
  anon_sym_COLON = 15,
  anon_sym_QMARK_COLON = 16,
  anon_sym_EQ = 17,
  anon_sym_POUND = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_PIPE = 21,
  anon_sym_DOT_DOT = 22,
  sym_integer = 23,
  anon_sym_DOT = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_string_token1 = 26,
  sym_program = 27,
  sym__harness = 28,
  sym_namespace = 29,
  sym_object = 30,
  sym_record = 31,
  sym_function = 32,
  sym_get = 33,
  sym_post = 34,
  sym_properties = 35,
  sym_property = 36,
  sym_optional = 37,
  sym_param = 38,
  sym__type = 39,
  sym_type = 40,
  sym_ref = 41,
  sym_array = 42,
  sym_union = 43,
  sym__slice = 44,
  sym_slice = 45,
  sym_nsid = 46,
  sym_string = 47,
  aux_sym_program_repeat1 = 48,
  aux_sym_namespace_repeat1 = 49,
  aux_sym_properties_repeat1 = 50,
  aux_sym_type_repeat1 = 51,
  aux_sym_nsid_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_AT_AT_LBRACK] = "@@[",
  [anon_sym_RBRACK_AT_AT] = "]@@",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_get] = "get",
  [anon_sym_post] = "post",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK_COLON] = "\?:",
  [anon_sym_EQ] = "=",
  [anon_sym_POUND] = "#",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PIPE] = "|",
  [anon_sym_DOT_DOT] = "..",
  [sym_integer] = "integer",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_program] = "program",
  [sym__harness] = "_harness",
  [sym_namespace] = "namespace",
  [sym_object] = "object",
  [sym_record] = "record",
  [sym_function] = "function",
  [sym_get] = "get",
  [sym_post] = "post",
  [sym_properties] = "properties",
  [sym_property] = "property",
  [sym_optional] = "optional",
  [sym_param] = "param",
  [sym__type] = "_type",
  [sym_type] = "type",
  [sym_ref] = "ref",
  [sym_array] = "array",
  [sym_union] = "union",
  [sym__slice] = "_slice",
  [sym_slice] = "slice",
  [sym_nsid] = "nsid",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_namespace_repeat1] = "namespace_repeat1",
  [aux_sym_properties_repeat1] = "properties_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
  [aux_sym_nsid_repeat1] = "nsid_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_AT_AT_LBRACK] = anon_sym_AT_AT_LBRACK,
  [anon_sym_RBRACK_AT_AT] = anon_sym_RBRACK_AT_AT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_post] = anon_sym_post,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK_COLON] = anon_sym_QMARK_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_integer] = sym_integer,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_program] = sym_program,
  [sym__harness] = sym__harness,
  [sym_namespace] = sym_namespace,
  [sym_object] = sym_object,
  [sym_record] = sym_record,
  [sym_function] = sym_function,
  [sym_get] = sym_get,
  [sym_post] = sym_post,
  [sym_properties] = sym_properties,
  [sym_property] = sym_property,
  [sym_optional] = sym_optional,
  [sym_param] = sym_param,
  [sym__type] = sym__type,
  [sym_type] = sym_type,
  [sym_ref] = sym_ref,
  [sym_array] = sym_array,
  [sym_union] = sym_union,
  [sym__slice] = sym__slice,
  [sym_slice] = sym_slice,
  [sym_nsid] = sym_nsid,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_namespace_repeat1] = aux_sym_namespace_repeat1,
  [aux_sym_properties_repeat1] = aux_sym_properties_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
  [aux_sym_nsid_repeat1] = aux_sym_nsid_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__harness] = {
    .visible = false,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_get] = {
    .visible = true,
    .named = true,
  },
  [sym_post] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_union] = {
    .visible = true,
    .named = true,
  },
  [sym__slice] = {
    .visible = false,
    .named = true,
  },
  [sym_slice] = {
    .visible = true,
    .named = true,
  },
  [sym_nsid] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_namespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_properties_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nsid_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_array = 1,
  field_body = 2,
  field_contents = 3,
  field_id = 4,
  field_max = 5,
  field_min = 6,
  field_name = 7,
  field_parameters = 8,
  field_type = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_array] = "array",
  [field_body] = "body",
  [field_contents] = "contents",
  [field_id] = "id",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 1},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
  [15] = {.index = 22, .length = 2},
  [16] = {.index = 24, .length = 2},
  [17] = {.index = 26, .length = 2},
  [18] = {.index = 28, .length = 2},
  [19] = {.index = 30, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_max, 0, .inherited = true},
    {field_min, 0, .inherited = true},
  [3] =
    {field_id, 1},
  [4] =
    {field_max, 1},
  [5] =
    {field_min, 0},
  [6] =
    {field_array, 1},
    {field_name, 0},
  [8] =
    {field_array, 2},
    {field_id, 1},
  [10] =
    {field_max, 1, .inherited = true},
    {field_min, 1, .inherited = true},
  [12] =
    {field_max, 2},
    {field_min, 0},
  [14] =
    {field_name, 0},
    {field_type, 2},
  [16] =
    {field_contents, 1},
  [17] =
    {field_name, 1},
  [18] =
    {field_body, 2},
    {field_name, 0},
  [20] =
    {field_array, 3},
    {field_name, 0},
  [22] =
    {field_body, 3},
    {field_name, 1},
  [24] =
    {field_array, 4},
    {field_name, 0},
  [26] =
    {field_body, 5},
    {field_name, 0},
  [28] =
    {field_name, 0},
    {field_parameters, 2},
  [30] =
    {field_body, 6},
    {field_name, 0},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 35,
        '#', 25,
        '(', 17,
        ')', 18,
        ',', 21,
        '-', 6,
        '.', 34,
        ':', 22,
        ';', 20,
        '=', 24,
        '?', 5,
        '@', 14,
        '[', 26,
        ']', 28,
        '{', 15,
        '|', 29,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 35,
        '#', 25,
        '(', 17,
        ')', 18,
        ',', 21,
        '-', 6,
        '.', 3,
        ':', 22,
        ';', 20,
        '=', 24,
        '?', 5,
        '[', 26,
        ']', 7,
        '{', 15,
        '|', 29,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 25,
        ')', 18,
        ',', 21,
        '.', 33,
        ';', 20,
        '[', 26,
        ']', 7,
        '{', 15,
        '|', 29,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ']') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == '@') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '@') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '[') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_AT_AT_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK_AT_AT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '@') ADVANCE(9);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_QMARK_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == '@') ADVANCE(8);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'g') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_post);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 36},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_AT_AT_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_AT_AT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_post] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(96),
    [sym__harness] = STATE(44),
    [sym_namespace] = STATE(44),
    [aux_sym_program_repeat1] = STATE(44),
    [anon_sym_AT_AT_LBRACK] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(5),
  },
  [2] = {
    [sym_object] = STATE(83),
    [sym_record] = STATE(83),
    [sym_function] = STATE(83),
    [sym_get] = STATE(83),
    [sym_post] = STATE(83),
    [sym_properties] = STATE(83),
    [sym_property] = STATE(54),
    [sym_optional] = STATE(54),
    [sym_param] = STATE(83),
    [sym__type] = STATE(86),
    [sym_type] = STATE(76),
    [sym_ref] = STATE(34),
    [sym_array] = STATE(83),
    [sym_union] = STATE(76),
    [sym__slice] = STATE(57),
    [sym_slice] = STATE(83),
    [sym_string] = STATE(83),
    [aux_sym_properties_repeat1] = STATE(16),
    [sym_id] = ACTIONS(7),
    [anon_sym_record] = ACTIONS(9),
    [anon_sym_get] = ACTIONS(11),
    [anon_sym_post] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_DOT_DOT] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(5), 1,
      aux_sym_nsid_repeat1,
    STATE(20), 1,
      sym_array,
    ACTIONS(25), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [23] = 3,
    ACTIONS(31), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(29), 10,
      anon_sym_RBRACK_AT_AT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
  [42] = 3,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(34), 10,
      anon_sym_RBRACK_AT_AT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
  [61] = 1,
    ACTIONS(29), 11,
      anon_sym_RBRACK_AT_AT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_DOT,
  [75] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_array,
    ACTIONS(36), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [95] = 7,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(40), 1,
      sym_id,
    ACTIONS(42), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_properties_repeat1,
    STATE(93), 1,
      sym_properties,
    STATE(60), 2,
      sym_param,
      aux_sym_type_repeat1,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [120] = 3,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_array,
    ACTIONS(25), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [137] = 6,
    ACTIONS(9), 1,
      anon_sym_record,
    ACTIONS(11), 1,
      anon_sym_get,
    ACTIONS(13), 1,
      anon_sym_post,
    ACTIONS(44), 1,
      sym_id,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(13), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [160] = 6,
    ACTIONS(9), 1,
      anon_sym_record,
    ACTIONS(11), 1,
      anon_sym_get,
    ACTIONS(13), 1,
      anon_sym_post,
    ACTIONS(44), 1,
      sym_id,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(10), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [183] = 3,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_array,
    ACTIONS(50), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [200] = 6,
    ACTIONS(52), 1,
      sym_id,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 1,
      anon_sym_record,
    ACTIONS(60), 1,
      anon_sym_get,
    ACTIONS(63), 1,
      anon_sym_post,
    STATE(13), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [223] = 3,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_array,
    ACTIONS(66), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [240] = 5,
    ACTIONS(68), 1,
      sym_id,
    ACTIONS(73), 1,
      anon_sym_POUND,
    STATE(15), 1,
      aux_sym_properties_repeat1,
    ACTIONS(71), 3,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [260] = 5,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    STATE(15), 1,
      aux_sym_properties_repeat1,
    ACTIONS(78), 3,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [280] = 8,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      anon_sym_QMARK_COLON,
    ACTIONS(88), 1,
      anon_sym_EQ,
    STATE(19), 1,
      sym_array,
    ACTIONS(36), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_PIPE,
  [306] = 1,
    ACTIONS(90), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [317] = 1,
    ACTIONS(92), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [328] = 1,
    ACTIONS(94), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [339] = 6,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_properties_repeat1,
    STATE(93), 1,
      sym_properties,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [360] = 6,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_properties_repeat1,
    STATE(89), 1,
      sym_properties,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [381] = 1,
    ACTIONS(100), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [392] = 2,
    ACTIONS(104), 1,
      anon_sym_PIPE,
    ACTIONS(102), 7,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      sym_id,
  [405] = 2,
    ACTIONS(104), 1,
      anon_sym_PIPE,
    ACTIONS(106), 7,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      sym_id,
  [418] = 1,
    ACTIONS(108), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [429] = 1,
    ACTIONS(110), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [440] = 1,
    ACTIONS(112), 8,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_id,
  [451] = 6,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_properties_repeat1,
    STATE(91), 1,
      sym_properties,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [472] = 6,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_properties_repeat1,
    STATE(95), 1,
      sym_properties,
    STATE(31), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [493] = 2,
    ACTIONS(120), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(118), 5,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [505] = 3,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
    ACTIONS(126), 1,
      sym_integer,
    ACTIONS(122), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [518] = 5,
    ACTIONS(19), 1,
      anon_sym_DOT_DOT,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(128), 1,
      sym_integer,
    STATE(57), 1,
      sym__slice,
    STATE(61), 2,
      sym_slice,
      sym_string,
  [535] = 4,
    ACTIONS(130), 1,
      anon_sym_RBRACK_AT_AT,
    ACTIONS(132), 1,
      anon_sym_PIPE,
    ACTIONS(118), 2,
      anon_sym_POUND,
      sym_id,
    ACTIONS(120), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [550] = 3,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      sym_id,
    STATE(25), 4,
      sym__type,
      sym_type,
      sym_ref,
      sym_union,
  [563] = 3,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      sym_id,
    STATE(24), 4,
      sym__type,
      sym_type,
      sym_ref,
      sym_union,
  [576] = 3,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      sym_id,
    STATE(26), 4,
      sym__type,
      sym_type,
      sym_ref,
      sym_union,
  [589] = 2,
    ACTIONS(138), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(136), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [600] = 2,
    ACTIONS(142), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(140), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [611] = 3,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    ACTIONS(148), 1,
      sym_integer,
    ACTIONS(144), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [624] = 4,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      anon_sym_AT_AT_LBRACK,
    ACTIONS(155), 1,
      anon_sym_AT,
    STATE(41), 3,
      sym__harness,
      sym_namespace,
      aux_sym_program_repeat1,
  [639] = 2,
    ACTIONS(160), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(158), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [650] = 2,
    ACTIONS(164), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(162), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [661] = 4,
    ACTIONS(3), 1,
      anon_sym_AT_AT_LBRACK,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    STATE(41), 3,
      sym__harness,
      sym_namespace,
      aux_sym_program_repeat1,
  [676] = 2,
    ACTIONS(170), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(168), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [687] = 2,
    ACTIONS(174), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(172), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [698] = 2,
    ACTIONS(178), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(176), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [709] = 2,
    ACTIONS(182), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(180), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [720] = 2,
    ACTIONS(186), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
    ACTIONS(184), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [731] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(188), 1,
      anon_sym_DASH_GT,
    STATE(28), 1,
      sym_array,
    ACTIONS(66), 2,
      anon_sym_RBRACK_AT_AT,
      anon_sym_PIPE,
  [745] = 2,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    ACTIONS(190), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [755] = 2,
    ACTIONS(196), 1,
      anon_sym_RBRACK,
    ACTIONS(194), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [765] = 1,
    ACTIONS(71), 5,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [773] = 3,
    ACTIONS(130), 1,
      anon_sym_RBRACK_AT_AT,
    ACTIONS(118), 2,
      anon_sym_POUND,
      sym_id,
    ACTIONS(120), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [785] = 3,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_DOT_DOT,
    ACTIONS(198), 3,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      sym_id,
  [797] = 1,
    ACTIONS(204), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [804] = 1,
    ACTIONS(206), 4,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [811] = 4,
    ACTIONS(19), 1,
      anon_sym_DOT_DOT,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
    ACTIONS(210), 1,
      sym_integer,
    STATE(92), 1,
      sym__slice,
  [824] = 3,
    ACTIONS(212), 1,
      sym_id,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(60), 2,
      sym_param,
      aux_sym_type_repeat1,
  [835] = 3,
    ACTIONS(212), 1,
      sym_id,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(62), 2,
      sym_param,
      aux_sym_type_repeat1,
  [846] = 2,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(198), 3,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      sym_id,
  [855] = 3,
    ACTIONS(218), 1,
      sym_id,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(62), 2,
      sym_param,
      aux_sym_type_repeat1,
  [866] = 2,
    ACTIONS(225), 1,
      anon_sym_AT,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      anon_sym_AT_AT_LBRACK,
  [874] = 3,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      anon_sym_QMARK_COLON,
    ACTIONS(88), 1,
      anon_sym_EQ,
  [884] = 2,
    ACTIONS(229), 1,
      anon_sym_AT,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_AT_AT_LBRACK,
  [892] = 1,
    ACTIONS(231), 3,
      anon_sym_RBRACK_AT_AT,
      anon_sym_RPAREN,
      sym_id,
  [898] = 2,
    ACTIONS(235), 1,
      anon_sym_AT,
    ACTIONS(233), 2,
      ts_builtin_sym_end,
      anon_sym_AT_AT_LBRACK,
  [906] = 2,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(5), 1,
      aux_sym_nsid_repeat1,
  [913] = 2,
    ACTIONS(237), 1,
      sym_id,
    STATE(43), 1,
      sym_function,
  [920] = 2,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      anon_sym_QMARK_COLON,
  [927] = 2,
    ACTIONS(239), 1,
      sym_id,
    STATE(42), 1,
      sym_object,
  [934] = 2,
    ACTIONS(241), 1,
      sym_id,
    STATE(85), 1,
      sym_nsid,
  [941] = 2,
    ACTIONS(243), 1,
      sym_id,
    STATE(9), 1,
      sym_nsid,
  [948] = 2,
    ACTIONS(130), 1,
      anon_sym_RBRACK_AT_AT,
    ACTIONS(202), 1,
      anon_sym_DOT_DOT,
  [955] = 2,
    ACTIONS(237), 1,
      sym_id,
    STATE(45), 1,
      sym_function,
  [962] = 2,
    ACTIONS(130), 1,
      anon_sym_RBRACK_AT_AT,
    ACTIONS(132), 1,
      anon_sym_PIPE,
  [969] = 1,
    ACTIONS(245), 1,
      anon_sym_LPAREN,
  [973] = 1,
    ACTIONS(188), 1,
      anon_sym_DASH_GT,
  [977] = 1,
    ACTIONS(247), 1,
      aux_sym_string_token1,
  [981] = 1,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
  [985] = 1,
    ACTIONS(251), 1,
      sym_id,
  [989] = 1,
    ACTIONS(253), 1,
      anon_sym_DASH_GT,
  [993] = 1,
    ACTIONS(130), 1,
      anon_sym_RBRACK_AT_AT,
  [997] = 1,
    ACTIONS(88), 1,
      anon_sym_EQ,
  [1001] = 1,
    ACTIONS(255), 1,
      anon_sym_LBRACE,
  [1005] = 1,
    ACTIONS(104), 1,
      anon_sym_PIPE,
  [1009] = 1,
    ACTIONS(202), 1,
      anon_sym_DOT_DOT,
  [1013] = 1,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
  [1017] = 1,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
  [1021] = 1,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
  [1025] = 1,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
  [1029] = 1,
    ACTIONS(263), 1,
      anon_sym_RBRACK,
  [1033] = 1,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
  [1037] = 1,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
  [1041] = 1,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
  [1045] = 1,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 23,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 61,
  [SMALL_STATE(7)] = 75,
  [SMALL_STATE(8)] = 95,
  [SMALL_STATE(9)] = 120,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 160,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 200,
  [SMALL_STATE(14)] = 223,
  [SMALL_STATE(15)] = 240,
  [SMALL_STATE(16)] = 260,
  [SMALL_STATE(17)] = 280,
  [SMALL_STATE(18)] = 306,
  [SMALL_STATE(19)] = 317,
  [SMALL_STATE(20)] = 328,
  [SMALL_STATE(21)] = 339,
  [SMALL_STATE(22)] = 360,
  [SMALL_STATE(23)] = 381,
  [SMALL_STATE(24)] = 392,
  [SMALL_STATE(25)] = 405,
  [SMALL_STATE(26)] = 418,
  [SMALL_STATE(27)] = 429,
  [SMALL_STATE(28)] = 440,
  [SMALL_STATE(29)] = 451,
  [SMALL_STATE(30)] = 472,
  [SMALL_STATE(31)] = 493,
  [SMALL_STATE(32)] = 505,
  [SMALL_STATE(33)] = 518,
  [SMALL_STATE(34)] = 535,
  [SMALL_STATE(35)] = 550,
  [SMALL_STATE(36)] = 563,
  [SMALL_STATE(37)] = 576,
  [SMALL_STATE(38)] = 589,
  [SMALL_STATE(39)] = 600,
  [SMALL_STATE(40)] = 611,
  [SMALL_STATE(41)] = 624,
  [SMALL_STATE(42)] = 639,
  [SMALL_STATE(43)] = 650,
  [SMALL_STATE(44)] = 661,
  [SMALL_STATE(45)] = 676,
  [SMALL_STATE(46)] = 687,
  [SMALL_STATE(47)] = 698,
  [SMALL_STATE(48)] = 709,
  [SMALL_STATE(49)] = 720,
  [SMALL_STATE(50)] = 731,
  [SMALL_STATE(51)] = 745,
  [SMALL_STATE(52)] = 755,
  [SMALL_STATE(53)] = 765,
  [SMALL_STATE(54)] = 773,
  [SMALL_STATE(55)] = 785,
  [SMALL_STATE(56)] = 797,
  [SMALL_STATE(57)] = 804,
  [SMALL_STATE(58)] = 811,
  [SMALL_STATE(59)] = 824,
  [SMALL_STATE(60)] = 835,
  [SMALL_STATE(61)] = 846,
  [SMALL_STATE(62)] = 855,
  [SMALL_STATE(63)] = 866,
  [SMALL_STATE(64)] = 874,
  [SMALL_STATE(65)] = 884,
  [SMALL_STATE(66)] = 892,
  [SMALL_STATE(67)] = 898,
  [SMALL_STATE(68)] = 906,
  [SMALL_STATE(69)] = 913,
  [SMALL_STATE(70)] = 920,
  [SMALL_STATE(71)] = 927,
  [SMALL_STATE(72)] = 934,
  [SMALL_STATE(73)] = 941,
  [SMALL_STATE(74)] = 948,
  [SMALL_STATE(75)] = 955,
  [SMALL_STATE(76)] = 962,
  [SMALL_STATE(77)] = 969,
  [SMALL_STATE(78)] = 973,
  [SMALL_STATE(79)] = 977,
  [SMALL_STATE(80)] = 981,
  [SMALL_STATE(81)] = 985,
  [SMALL_STATE(82)] = 989,
  [SMALL_STATE(83)] = 993,
  [SMALL_STATE(84)] = 997,
  [SMALL_STATE(85)] = 1001,
  [SMALL_STATE(86)] = 1005,
  [SMALL_STATE(87)] = 1009,
  [SMALL_STATE(88)] = 1013,
  [SMALL_STATE(89)] = 1017,
  [SMALL_STATE(90)] = 1021,
  [SMALL_STATE(91)] = 1025,
  [SMALL_STATE(92)] = 1029,
  [SMALL_STATE(93)] = 1033,
  [SMALL_STATE(94)] = 1037,
  [SMALL_STATE(95)] = 1041,
  [SMALL_STATE(96)] = 1045,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2, 0, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nsid, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 1),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 1),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 6),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 3, 0, 7),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 10),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 3, 0, 10),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 16),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 14),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 2, 0, 5),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__slice, 2, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 8, 0, 19),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 19),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__slice, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 13),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 13),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 6, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 17),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 17),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 18),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 18),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 2, 0, 4),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__slice, 2, 0, 4),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 3, 0, 9),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__slice, 3, 0, 9),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 11),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice, 1, 0, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 5, 0, 15),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 5, 0, 15),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4, 0, 12),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 4, 0, 12),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__harness, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__harness, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [271] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ana(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
