#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 19

enum ts_symbol_identifiers {
  sym_id = 1,
  anon_sym_AT = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_record = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_get = 9,
  anon_sym_post = 10,
  anon_sym_SEMI = 11,
  anon_sym_COMMA = 12,
  anon_sym_COLON = 13,
  anon_sym_QMARK_COLON = 14,
  anon_sym_EQ = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_PIPE = 18,
  anon_sym_DOT_DOT = 19,
  sym_integer = 20,
  anon_sym_DOT = 21,
  anon_sym_POUND = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_token1 = 24,
  sym_program = 25,
  sym_namespace = 26,
  sym_object = 27,
  sym_record = 28,
  sym_function = 29,
  sym_get = 30,
  sym_post = 31,
  sym_properties = 32,
  sym_property = 33,
  sym_optional = 34,
  sym__type = 35,
  sym_type = 36,
  sym_param = 37,
  sym_array = 38,
  sym_union = 39,
  sym__slice = 40,
  sym_nsid = 41,
  sym_ref = 42,
  sym_string = 43,
  aux_sym_program_repeat1 = 44,
  aux_sym_namespace_repeat1 = 45,
  aux_sym_properties_repeat1 = 46,
  aux_sym_type_repeat1 = 47,
  aux_sym_nsid_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_get] = "get",
  [anon_sym_post] = "post",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK_COLON] = "\?:",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PIPE] = "|",
  [anon_sym_DOT_DOT] = "..",
  [sym_integer] = "integer",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_program] = "program",
  [sym_namespace] = "namespace",
  [sym_object] = "object",
  [sym_record] = "record",
  [sym_function] = "function",
  [sym_get] = "get",
  [sym_post] = "post",
  [sym_properties] = "properties",
  [sym_property] = "property",
  [sym_optional] = "optional",
  [sym__type] = "_type",
  [sym_type] = "type",
  [sym_param] = "param",
  [sym_array] = "array",
  [sym_union] = "union",
  [sym__slice] = "_slice",
  [sym_nsid] = "nsid",
  [sym_ref] = "ref",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_namespace_repeat1] = "namespace_repeat1",
  [aux_sym_properties_repeat1] = "properties_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
  [aux_sym_nsid_repeat1] = "nsid_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_post] = anon_sym_post,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK_COLON] = anon_sym_QMARK_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_integer] = sym_integer,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_program] = sym_program,
  [sym_namespace] = sym_namespace,
  [sym_object] = sym_object,
  [sym_record] = sym_record,
  [sym_function] = sym_function,
  [sym_get] = sym_get,
  [sym_post] = sym_post,
  [sym_properties] = sym_properties,
  [sym_property] = sym_property,
  [sym_optional] = sym_optional,
  [sym__type] = sym__type,
  [sym_type] = sym_type,
  [sym_param] = sym_param,
  [sym_array] = sym_array,
  [sym_union] = sym_union,
  [sym__slice] = sym__slice,
  [sym_nsid] = sym_nsid,
  [sym_ref] = sym_ref,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_namespace_repeat1] = aux_sym_namespace_repeat1,
  [aux_sym_properties_repeat1] = aux_sym_properties_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
  [aux_sym_nsid_repeat1] = aux_sym_nsid_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_get] = {
    .visible = true,
    .named = true,
  },
  [sym_post] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_union] = {
    .visible = true,
    .named = true,
  },
  [sym__slice] = {
    .visible = false,
    .named = true,
  },
  [sym_nsid] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_namespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_properties_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nsid_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_contents = 2,
  field_id = 3,
  field_integer = 4,
  field_max = 5,
  field_min = 6,
  field_name = 7,
  field_parameters = 8,
  field_slice = 9,
  field_string = 10,
  field_type = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_contents] = "contents",
  [field_id] = "id",
  [field_integer] = "integer",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_slice] = "slice",
  [field_string] = "string",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 3},
  [13] = {.index = 19, .length = 3},
  [14] = {.index = 22, .length = 2},
  [15] = {.index = 24, .length = 4},
  [16] = {.index = 28, .length = 2},
  [17] = {.index = 30, .length = 2},
  [18] = {.index = 32, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_body, 3},
    {field_name, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_id, 1},
  [5] =
    {field_body, 2},
    {field_name, 0},
  [7] =
    {field_name, 0},
    {field_type, 2},
  [9] =
    {field_type, 0},
  [10] =
    {field_body, 5},
    {field_name, 0},
  [12] =
    {field_name, 0},
    {field_parameters, 2},
  [14] =
    {field_max, 1},
  [15] =
    {field_min, 0},
  [16] =
    {field_max, 2, .inherited = true},
    {field_min, 2, .inherited = true},
    {field_type, 0},
  [19] =
    {field_body, 6},
    {field_name, 0},
    {field_parameters, 2},
  [22] =
    {field_integer, 2},
    {field_name, 0},
  [24] =
    {field_max, 2, .inherited = true},
    {field_min, 2, .inherited = true},
    {field_name, 0},
    {field_slice, 2},
  [28] =
    {field_name, 0},
    {field_string, 2},
  [30] =
    {field_max, 2},
    {field_min, 0},
  [32] =
    {field_contents, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 28,
        '#', 27,
        '(', 11,
        ')', 12,
        ',', 15,
        '-', 5,
        '.', 26,
        ':', 16,
        ';', 14,
        '=', 18,
        '?', 4,
        '@', 8,
        '[', 19,
        ']', 20,
        '{', 9,
        '|', 21,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == ',') ADVANCE(15);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ']') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 27,
        ')', 12,
        ',', 15,
        '.', 25,
        ';', 14,
        '[', 19,
        '{', 9,
        '|', 21,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_QMARK_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(22);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'g') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_post);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 29},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_post] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(74),
    [sym_namespace] = STATE(42),
    [aux_sym_program_repeat1] = STATE(42),
    [anon_sym_AT] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(3), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(5), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [18] = 3,
    ACTIONS(11), 1,
      anon_sym_DOT,
    STATE(3), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(9), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [36] = 1,
    ACTIONS(9), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_DOT,
      anon_sym_POUND,
  [49] = 6,
    ACTIONS(14), 1,
      sym_id,
    ACTIONS(16), 1,
      anon_sym_RBRACE,
    ACTIONS(18), 1,
      anon_sym_record,
    ACTIONS(20), 1,
      anon_sym_get,
    ACTIONS(22), 1,
      anon_sym_post,
    STATE(6), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [72] = 6,
    ACTIONS(24), 1,
      sym_id,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      anon_sym_record,
    ACTIONS(32), 1,
      anon_sym_get,
    ACTIONS(35), 1,
      anon_sym_post,
    STATE(6), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [95] = 3,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(2), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(38), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [112] = 6,
    ACTIONS(14), 1,
      sym_id,
    ACTIONS(18), 1,
      anon_sym_record,
    ACTIONS(20), 1,
      anon_sym_get,
    ACTIONS(22), 1,
      anon_sym_post,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(5), 5,
      sym_object,
      sym_record,
      sym_get,
      sym_post,
      aux_sym_namespace_repeat1,
  [135] = 2,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [149] = 5,
    ACTIONS(46), 1,
      sym_id,
    ACTIONS(51), 1,
      anon_sym_POUND,
    STATE(10), 1,
      aux_sym_properties_repeat1,
    ACTIONS(49), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [168] = 6,
    ACTIONS(54), 1,
      sym_id,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(58), 1,
      anon_sym_POUND,
    STATE(13), 1,
      aux_sym_properties_repeat1,
    STATE(79), 1,
      sym_properties,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [189] = 6,
    ACTIONS(54), 1,
      sym_id,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      aux_sym_properties_repeat1,
    STATE(81), 1,
      sym_properties,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [210] = 5,
    ACTIONS(54), 1,
      sym_id,
    ACTIONS(58), 1,
      anon_sym_POUND,
    STATE(10), 1,
      aux_sym_properties_repeat1,
    ACTIONS(62), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [229] = 2,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 7,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [242] = 1,
    ACTIONS(38), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [253] = 6,
    ACTIONS(54), 1,
      sym_id,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      aux_sym_properties_repeat1,
    STATE(72), 1,
      sym_properties,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [274] = 1,
    ACTIONS(70), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [285] = 1,
    ACTIONS(72), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [296] = 6,
    ACTIONS(54), 1,
      sym_id,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      aux_sym_properties_repeat1,
    STATE(82), 1,
      sym_properties,
    STATE(28), 3,
      sym_property,
      sym_optional,
      sym_ref,
  [317] = 4,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    STATE(14), 2,
      sym_type,
      sym_ref,
    STATE(23), 3,
      sym__type,
      sym_array,
      sym_union,
  [333] = 2,
    ACTIONS(80), 1,
      anon_sym_PIPE,
    ACTIONS(78), 6,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_id,
      anon_sym_POUND,
  [345] = 4,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    STATE(14), 2,
      sym_type,
      sym_ref,
    STATE(21), 3,
      sym__type,
      sym_array,
      sym_union,
  [361] = 2,
    ACTIONS(80), 1,
      anon_sym_PIPE,
    ACTIONS(82), 6,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_id,
      anon_sym_POUND,
  [373] = 4,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_id,
    STATE(14), 2,
      sym_type,
      sym_ref,
    STATE(25), 3,
      sym__type,
      sym_array,
      sym_union,
  [389] = 1,
    ACTIONS(84), 7,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [399] = 1,
    ACTIONS(86), 7,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [409] = 1,
    ACTIONS(88), 7,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_PIPE,
      sym_id,
      anon_sym_POUND,
  [419] = 2,
    ACTIONS(92), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(90), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_id,
      anon_sym_POUND,
  [430] = 2,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [440] = 2,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [450] = 2,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [460] = 2,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    ACTIONS(106), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [470] = 2,
    ACTIONS(112), 1,
      sym_integer,
    ACTIONS(110), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_id,
  [480] = 2,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [490] = 2,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [500] = 5,
    ACTIONS(122), 1,
      anon_sym_DOT_DOT,
    ACTIONS(124), 1,
      sym_integer,
    ACTIONS(126), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      sym_string,
    STATE(53), 1,
      sym__slice,
  [516] = 2,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [526] = 2,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [536] = 2,
    ACTIONS(138), 1,
      sym_integer,
    ACTIONS(136), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_id,
  [546] = 2,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 4,
      anon_sym_record,
      anon_sym_get,
      anon_sym_post,
      sym_id,
  [556] = 1,
    ACTIONS(144), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_id,
  [563] = 3,
    ACTIONS(3), 1,
      anon_sym_AT,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    STATE(46), 2,
      sym_namespace,
      aux_sym_program_repeat1,
  [574] = 4,
    ACTIONS(122), 1,
      anon_sym_DOT_DOT,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    ACTIONS(150), 1,
      sym_integer,
    STATE(78), 1,
      sym__slice,
  [587] = 3,
    ACTIONS(152), 1,
      sym_id,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(45), 2,
      sym_param,
      aux_sym_type_repeat1,
  [598] = 3,
    ACTIONS(152), 1,
      sym_id,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(48), 2,
      sym_param,
      aux_sym_type_repeat1,
  [609] = 3,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 1,
      anon_sym_AT,
    STATE(46), 2,
      sym_namespace,
      aux_sym_program_repeat1,
  [620] = 1,
    ACTIONS(163), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_id,
  [627] = 3,
    ACTIONS(165), 1,
      sym_id,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    STATE(48), 2,
      sym_param,
      aux_sym_type_repeat1,
  [638] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_DOT_DOT,
    ACTIONS(170), 2,
      anon_sym_RPAREN,
      sym_id,
  [649] = 1,
    ACTIONS(49), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_id,
      anon_sym_POUND,
  [656] = 1,
    ACTIONS(176), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_id,
  [662] = 2,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(178), 2,
      anon_sym_RPAREN,
      sym_id,
  [670] = 2,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      sym_id,
  [678] = 2,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(2), 1,
      aux_sym_nsid_repeat1,
  [685] = 1,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
  [690] = 1,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      anon_sym_AT,
  [695] = 2,
    ACTIONS(190), 1,
      sym_id,
    STATE(68), 1,
      sym_nsid,
  [702] = 2,
    ACTIONS(192), 1,
      anon_sym_COLON,
    ACTIONS(194), 1,
      anon_sym_QMARK_COLON,
  [709] = 2,
    ACTIONS(196), 1,
      sym_id,
    STATE(15), 1,
      sym_nsid,
  [716] = 2,
    ACTIONS(198), 1,
      sym_id,
    STATE(38), 1,
      sym_object,
  [723] = 2,
    ACTIONS(200), 1,
      sym_id,
    STATE(30), 1,
      sym_function,
  [730] = 2,
    ACTIONS(200), 1,
      sym_id,
    STATE(29), 1,
      sym_function,
  [737] = 1,
    ACTIONS(202), 2,
      anon_sym_RPAREN,
      sym_id,
  [742] = 1,
    ACTIONS(204), 2,
      anon_sym_RPAREN,
      sym_id,
  [747] = 1,
    ACTIONS(206), 2,
      anon_sym_RPAREN,
      sym_id,
  [752] = 1,
    ACTIONS(174), 1,
      anon_sym_DOT_DOT,
  [756] = 1,
    ACTIONS(208), 1,
      anon_sym_DASH_GT,
  [760] = 1,
    ACTIONS(210), 1,
      anon_sym_LBRACE,
  [764] = 1,
    ACTIONS(212), 1,
      anon_sym_EQ,
  [768] = 1,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
  [772] = 1,
    ACTIONS(216), 1,
      anon_sym_LPAREN,
  [776] = 1,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
  [780] = 1,
    ACTIONS(220), 1,
      sym_id,
  [784] = 1,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
  [788] = 1,
    ACTIONS(224), 1,
      aux_sym_string_token1,
  [792] = 1,
    ACTIONS(226), 1,
      anon_sym_DASH_GT,
  [796] = 1,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
  [800] = 1,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
  [804] = 1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [808] = 1,
    ACTIONS(234), 1,
      anon_sym_DQUOTE,
  [812] = 1,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
  [816] = 1,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [820] = 1,
    ACTIONS(240), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 95,
  [SMALL_STATE(8)] = 112,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 149,
  [SMALL_STATE(11)] = 168,
  [SMALL_STATE(12)] = 189,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 229,
  [SMALL_STATE(15)] = 242,
  [SMALL_STATE(16)] = 253,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 285,
  [SMALL_STATE(19)] = 296,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 333,
  [SMALL_STATE(22)] = 345,
  [SMALL_STATE(23)] = 361,
  [SMALL_STATE(24)] = 373,
  [SMALL_STATE(25)] = 389,
  [SMALL_STATE(26)] = 399,
  [SMALL_STATE(27)] = 409,
  [SMALL_STATE(28)] = 419,
  [SMALL_STATE(29)] = 430,
  [SMALL_STATE(30)] = 440,
  [SMALL_STATE(31)] = 450,
  [SMALL_STATE(32)] = 460,
  [SMALL_STATE(33)] = 470,
  [SMALL_STATE(34)] = 480,
  [SMALL_STATE(35)] = 490,
  [SMALL_STATE(36)] = 500,
  [SMALL_STATE(37)] = 516,
  [SMALL_STATE(38)] = 526,
  [SMALL_STATE(39)] = 536,
  [SMALL_STATE(40)] = 546,
  [SMALL_STATE(41)] = 556,
  [SMALL_STATE(42)] = 563,
  [SMALL_STATE(43)] = 574,
  [SMALL_STATE(44)] = 587,
  [SMALL_STATE(45)] = 598,
  [SMALL_STATE(46)] = 609,
  [SMALL_STATE(47)] = 620,
  [SMALL_STATE(48)] = 627,
  [SMALL_STATE(49)] = 638,
  [SMALL_STATE(50)] = 649,
  [SMALL_STATE(51)] = 656,
  [SMALL_STATE(52)] = 662,
  [SMALL_STATE(53)] = 670,
  [SMALL_STATE(54)] = 678,
  [SMALL_STATE(55)] = 685,
  [SMALL_STATE(56)] = 690,
  [SMALL_STATE(57)] = 695,
  [SMALL_STATE(58)] = 702,
  [SMALL_STATE(59)] = 709,
  [SMALL_STATE(60)] = 716,
  [SMALL_STATE(61)] = 723,
  [SMALL_STATE(62)] = 730,
  [SMALL_STATE(63)] = 737,
  [SMALL_STATE(64)] = 742,
  [SMALL_STATE(65)] = 747,
  [SMALL_STATE(66)] = 752,
  [SMALL_STATE(67)] = 756,
  [SMALL_STATE(68)] = 760,
  [SMALL_STATE(69)] = 764,
  [SMALL_STATE(70)] = 768,
  [SMALL_STATE(71)] = 772,
  [SMALL_STATE(72)] = 776,
  [SMALL_STATE(73)] = 780,
  [SMALL_STATE(74)] = 784,
  [SMALL_STATE(75)] = 788,
  [SMALL_STATE(76)] = 792,
  [SMALL_STATE(77)] = 796,
  [SMALL_STATE(78)] = 800,
  [SMALL_STATE(79)] = 804,
  [SMALL_STATE(80)] = 808,
  [SMALL_STATE(81)] = 812,
  [SMALL_STATE(82)] = 816,
  [SMALL_STATE(83)] = 820,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nsid, 2, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [14] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [16] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_namespace_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2, 0, 4),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 3),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 6),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 3, 0, 6),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 7),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 12),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 5),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 8),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 8),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7, 0, 9),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 9),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 6, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 2, 0, 11),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 8, 0, 13),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 13),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 2, 0, 10),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__slice, 3, 0, 17),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 14),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 18),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 16),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 15),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 5, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 14),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 15),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 16),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [222] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ana(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
