#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  sym_id = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_DOT = 4,
  sym_integer = 5,
  anon_sym_DOT_DOT = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_record = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_QMARK = 12,
  anon_sym_COLON = 13,
  anon_sym_EQ = 14,
  anon_sym_COMMA = 15,
  anon_sym_SEMI = 16,
  anon_sym_POUND = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_string_token1 = 19,
  sym_program = 20,
  sym_array = 21,
  sym_nsid = 22,
  sym_slice = 23,
  sym_block = 24,
  sym_scope = 25,
  sym_record = 26,
  sym_params = 27,
  sym_param = 28,
  sym_type = 29,
  sym_ref = 30,
  sym_string = 31,
  aux_sym_program_repeat1 = 32,
  aux_sym_nsid_repeat1 = 33,
  aux_sym_block_repeat1 = 34,
  aux_sym_block_repeat2 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [sym_integer] = "integer",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_record] = "record",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_POUND] = "#",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_program] = "program",
  [sym_array] = "array",
  [sym_nsid] = "nsid",
  [sym_slice] = "slice",
  [sym_block] = "block",
  [sym_scope] = "scope",
  [sym_record] = "record",
  [sym_params] = "params",
  [sym_param] = "param",
  [sym_type] = "type",
  [sym_ref] = "ref",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_nsid_repeat1] = "nsid_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_block_repeat2] = "block_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_integer] = sym_integer,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_program] = sym_program,
  [sym_array] = sym_array,
  [sym_nsid] = sym_nsid,
  [sym_slice] = sym_slice,
  [sym_block] = sym_block,
  [sym_scope] = sym_scope,
  [sym_record] = sym_record,
  [sym_params] = sym_params,
  [sym_param] = sym_param,
  [sym_type] = sym_type,
  [sym_ref] = sym_ref,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_nsid_repeat1] = aux_sym_nsid_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_block_repeat2] = aux_sym_block_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_nsid] = {
    .visible = true,
    .named = true,
  },
  [sym_slice] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nsid_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_array = 1,
  field_contents = 2,
  field_id = 3,
  field_max = 4,
  field_min = 5,
  field_name = 6,
  field_optional = 7,
  field_ref = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_array] = "array",
  [field_contents] = "contents",
  [field_id] = "id",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_optional] = "optional",
  [field_ref] = "ref",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 3},
  [12] = {.index = 19, .length = 2},
  [13] = {.index = 21, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_ref, 0},
  [1] =
    {field_id, 1},
  [2] =
    {field_optional, 1},
    {field_ref, 0},
  [4] =
    {field_array, 1},
    {field_ref, 0},
  [6] =
    {field_name, 0},
  [7] =
    {field_array, 2},
    {field_optional, 1},
    {field_ref, 0},
  [10] =
    {field_name, 0},
    {field_optional, 1},
  [12] =
    {field_min, 0},
  [13] =
    {field_max, 1},
  [14] =
    {field_array, 3},
    {field_name, 0},
  [16] =
    {field_array, 4},
    {field_name, 0},
    {field_optional, 1},
  [19] =
    {field_max, 2},
    {field_min, 0},
  [21] =
    {field_contents, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 22,
        '#', 21,
        '(', 14,
        ')', 15,
        ',', 19,
        '.', 9,
        ':', 17,
        ';', 20,
        '=', 18,
        '?', 16,
        '[', 6,
        ']', 7,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ']') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 21,
        ')', 15,
        ',', 19,
        '.', 8,
        ':', 17,
        ';', 20,
        '=', 18,
        '?', 16,
        '[', 6,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 23},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(61),
    [sym_nsid] = STATE(54),
    [sym_scope] = STATE(37),
    [aux_sym_program_repeat1] = STATE(37),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_id] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      sym_id,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(13), 1,
      anon_sym_POUND,
    STATE(7), 1,
      sym_ref,
    STATE(54), 1,
      sym_nsid,
    STATE(35), 2,
      sym_param,
      aux_sym_block_repeat1,
    STATE(25), 3,
      sym_scope,
      sym_record,
      aux_sym_block_repeat2,
  [28] = 3,
    ACTIONS(17), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(15), 9,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_QMARK,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [46] = 3,
    ACTIONS(21), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(19), 9,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_QMARK,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [64] = 1,
    ACTIONS(19), 10,
      anon_sym_LBRACK,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_QMARK,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [77] = 3,
    ACTIONS(17), 1,
      anon_sym_DOT,
    STATE(3), 1,
      aux_sym_nsid_repeat1,
    ACTIONS(24), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_QMARK,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [94] = 5,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(30), 1,
      anon_sym_QMARK,
    STATE(29), 1,
      sym_array,
    ACTIONS(32), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(26), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [114] = 6,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(34), 1,
      sym_id,
    ACTIONS(36), 1,
      sym_integer,
    ACTIONS(38), 1,
      anon_sym_DOT_DOT,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    STATE(17), 4,
      sym_slice,
      sym_type,
      sym_ref,
      sym_string,
  [136] = 6,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(34), 1,
      sym_id,
    ACTIONS(36), 1,
      sym_integer,
    ACTIONS(38), 1,
      anon_sym_DOT_DOT,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    STATE(15), 4,
      sym_slice,
      sym_type,
      sym_ref,
      sym_string,
  [158] = 3,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_params,
    ACTIONS(42), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [174] = 2,
    ACTIONS(48), 1,
      sym_integer,
    ACTIONS(46), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [188] = 2,
    ACTIONS(52), 1,
      sym_integer,
    ACTIONS(50), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [202] = 1,
    ACTIONS(24), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_QMARK,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [213] = 4,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_array,
    ACTIONS(56), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(54), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [230] = 4,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    STATE(34), 1,
      sym_array,
    ACTIONS(60), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(58), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [247] = 1,
    ACTIONS(62), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [258] = 4,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_array,
    ACTIONS(66), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(64), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [275] = 1,
    ACTIONS(68), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [286] = 1,
    ACTIONS(70), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [296] = 5,
    ACTIONS(72), 1,
      sym_id,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 1,
      anon_sym_record,
    STATE(54), 1,
      sym_nsid,
    STATE(20), 3,
      sym_scope,
      sym_record,
      aux_sym_block_repeat2,
  [314] = 5,
    ACTIONS(80), 1,
      sym_id,
    ACTIONS(85), 1,
      anon_sym_POUND,
    STATE(7), 1,
      sym_ref,
    ACTIONS(83), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(21), 2,
      sym_param,
      aux_sym_block_repeat1,
  [332] = 6,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 1,
      anon_sym_QMARK,
    STATE(3), 1,
      aux_sym_nsid_repeat1,
    STATE(42), 1,
      sym_block,
    ACTIONS(92), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [352] = 1,
    ACTIONS(94), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [362] = 1,
    ACTIONS(96), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [372] = 5,
    ACTIONS(11), 1,
      anon_sym_record,
    ACTIONS(98), 1,
      sym_id,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym_nsid,
    STATE(20), 3,
      sym_scope,
      sym_record,
      aux_sym_block_repeat2,
  [390] = 1,
    ACTIONS(102), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [400] = 2,
    ACTIONS(106), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(104), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [411] = 1,
    ACTIONS(108), 6,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [420] = 2,
    ACTIONS(112), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(110), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [431] = 5,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      sym_id,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_ref,
    STATE(32), 2,
      sym_param,
      aux_sym_block_repeat1,
  [448] = 2,
    ACTIONS(120), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(118), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [459] = 5,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      sym_id,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_ref,
    STATE(21), 2,
      sym_param,
      aux_sym_block_repeat1,
  [476] = 1,
    ACTIONS(124), 6,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_POUND,
      sym_id,
  [485] = 2,
    ACTIONS(128), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(126), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [496] = 5,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 1,
      sym_id,
    STATE(7), 1,
      sym_ref,
    STATE(21), 2,
      sym_param,
      aux_sym_block_repeat1,
  [513] = 4,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      sym_id,
    STATE(54), 1,
      sym_nsid,
    STATE(36), 2,
      sym_scope,
      aux_sym_program_repeat1,
  [527] = 4,
    ACTIONS(5), 1,
      sym_id,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      sym_nsid,
    STATE(36), 2,
      sym_scope,
      aux_sym_program_repeat1,
  [541] = 4,
    ACTIONS(36), 1,
      sym_integer,
    ACTIONS(38), 1,
      anon_sym_DOT_DOT,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_slice,
  [554] = 1,
    ACTIONS(139), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [561] = 2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(143), 2,
      anon_sym_record,
      sym_id,
  [570] = 2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(147), 2,
      anon_sym_record,
      sym_id,
  [579] = 2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(151), 2,
      anon_sym_record,
      sym_id,
  [588] = 1,
    ACTIONS(153), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [595] = 4,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      aux_sym_nsid_repeat1,
    STATE(42), 1,
      sym_block,
  [608] = 1,
    ACTIONS(155), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [615] = 1,
    ACTIONS(157), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [622] = 1,
    ACTIONS(159), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [629] = 1,
    ACTIONS(161), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [636] = 1,
    ACTIONS(163), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [643] = 1,
    ACTIONS(165), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym_id,
  [650] = 2,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 2,
      anon_sym_record,
      sym_id,
  [658] = 2,
    ACTIONS(90), 1,
      anon_sym_QMARK,
    ACTIONS(92), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [666] = 3,
    ACTIONS(5), 1,
      sym_id,
    STATE(51), 1,
      sym_scope,
    STATE(54), 1,
      sym_nsid,
  [676] = 2,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
  [683] = 2,
    ACTIONS(171), 1,
      sym_id,
    STATE(13), 1,
      sym_nsid,
  [690] = 1,
    ACTIONS(173), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [695] = 1,
    ACTIONS(175), 1,
      aux_sym_string_token1,
  [699] = 1,
    ACTIONS(177), 1,
      sym_id,
  [703] = 1,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
  [707] = 1,
    ACTIONS(181), 1,
      anon_sym_DOT_DOT,
  [711] = 1,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
  [715] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 77,
  [SMALL_STATE(7)] = 94,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 136,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 174,
  [SMALL_STATE(12)] = 188,
  [SMALL_STATE(13)] = 202,
  [SMALL_STATE(14)] = 213,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 247,
  [SMALL_STATE(17)] = 258,
  [SMALL_STATE(18)] = 275,
  [SMALL_STATE(19)] = 286,
  [SMALL_STATE(20)] = 296,
  [SMALL_STATE(21)] = 314,
  [SMALL_STATE(22)] = 332,
  [SMALL_STATE(23)] = 352,
  [SMALL_STATE(24)] = 362,
  [SMALL_STATE(25)] = 372,
  [SMALL_STATE(26)] = 390,
  [SMALL_STATE(27)] = 400,
  [SMALL_STATE(28)] = 411,
  [SMALL_STATE(29)] = 420,
  [SMALL_STATE(30)] = 431,
  [SMALL_STATE(31)] = 448,
  [SMALL_STATE(32)] = 459,
  [SMALL_STATE(33)] = 476,
  [SMALL_STATE(34)] = 485,
  [SMALL_STATE(35)] = 496,
  [SMALL_STATE(36)] = 513,
  [SMALL_STATE(37)] = 527,
  [SMALL_STATE(38)] = 541,
  [SMALL_STATE(39)] = 554,
  [SMALL_STATE(40)] = 561,
  [SMALL_STATE(41)] = 570,
  [SMALL_STATE(42)] = 579,
  [SMALL_STATE(43)] = 588,
  [SMALL_STATE(44)] = 595,
  [SMALL_STATE(45)] = 608,
  [SMALL_STATE(46)] = 615,
  [SMALL_STATE(47)] = 622,
  [SMALL_STATE(48)] = 629,
  [SMALL_STATE(49)] = 636,
  [SMALL_STATE(50)] = 643,
  [SMALL_STATE(51)] = 650,
  [SMALL_STATE(52)] = 658,
  [SMALL_STATE(53)] = 666,
  [SMALL_STATE(54)] = 676,
  [SMALL_STATE(55)] = 683,
  [SMALL_STATE(56)] = 690,
  [SMALL_STATE(57)] = 695,
  [SMALL_STATE(58)] = 699,
  [SMALL_STATE(59)] = 703,
  [SMALL_STATE(60)] = 707,
  [SMALL_STATE(61)] = 711,
  [SMALL_STATE(62)] = 715,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nsid, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nsid_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2, 0, 2),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice, 2, 0, 8),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 7),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice, 2, 0, 9),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 5),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice, 3, 0, 12),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2, 0, 0), SHIFT_REPEAT(44),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat2, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat2, 2, 0, 0), SHIFT_REPEAT(53),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 13),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 6),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 10),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 11),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 3),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 6),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 7),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 5),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 10),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 6, 0, 11),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [183] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ana(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
